apiVersion: v1
kind: ServiceAccount
metadata:
  name: koordlet
  namespace: koord-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: koordlet-custom-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: koordlet-cluserrole
subjects:
  - kind: ServiceAccount
    name: koordlet
    namespace: koord-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: koordlet-cluserrole
rules:
  - apiGroups:
      - config.koordinator.sh
      - slo.koordinator.sh
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/status
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
      - pods
      - pods/status
    verbs:
      - patch
      - update
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - '*'