/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	analysisv1alpha1 "github.com/koordinator-sh/koordinator/apis/analysis/v1alpha1"
	scheme "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RecommendationsGetter has a method to return a RecommendationInterface.
// A group's client should implement this interface.
type RecommendationsGetter interface {
	Recommendations(namespace string) RecommendationInterface
}

// RecommendationInterface has methods to work with Recommendation resources.
type RecommendationInterface interface {
	Create(ctx context.Context, recommendation *analysisv1alpha1.Recommendation, opts v1.CreateOptions) (*analysisv1alpha1.Recommendation, error)
	Update(ctx context.Context, recommendation *analysisv1alpha1.Recommendation, opts v1.UpdateOptions) (*analysisv1alpha1.Recommendation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, recommendation *analysisv1alpha1.Recommendation, opts v1.UpdateOptions) (*analysisv1alpha1.Recommendation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*analysisv1alpha1.Recommendation, error)
	List(ctx context.Context, opts v1.ListOptions) (*analysisv1alpha1.RecommendationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *analysisv1alpha1.Recommendation, err error)
	RecommendationExpansion
}

// recommendations implements RecommendationInterface
type recommendations struct {
	*gentype.ClientWithList[*analysisv1alpha1.Recommendation, *analysisv1alpha1.RecommendationList]
}

// newRecommendations returns a Recommendations
func newRecommendations(c *AnalysisV1alpha1Client, namespace string) *recommendations {
	return &recommendations{
		gentype.NewClientWithList[*analysisv1alpha1.Recommendation, *analysisv1alpha1.RecommendationList](
			"recommendations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *analysisv1alpha1.Recommendation { return &analysisv1alpha1.Recommendation{} },
			func() *analysisv1alpha1.RecommendationList { return &analysisv1alpha1.RecommendationList{} },
		),
	}
}
