/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/analysis/v1alpha1"
	scheme "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RecommendationsGetter has a method to return a RecommendationInterface.
// A group's client should implement this interface.
type RecommendationsGetter interface {
	Recommendations(namespace string) RecommendationInterface
}

// RecommendationInterface has methods to work with Recommendation resources.
type RecommendationInterface interface {
	Create(ctx context.Context, recommendation *v1alpha1.Recommendation, opts v1.CreateOptions) (*v1alpha1.Recommendation, error)
	Update(ctx context.Context, recommendation *v1alpha1.Recommendation, opts v1.UpdateOptions) (*v1alpha1.Recommendation, error)
	UpdateStatus(ctx context.Context, recommendation *v1alpha1.Recommendation, opts v1.UpdateOptions) (*v1alpha1.Recommendation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Recommendation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RecommendationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Recommendation, err error)
	RecommendationExpansion
}

// recommendations implements RecommendationInterface
type recommendations struct {
	client rest.Interface
	ns     string
}

// newRecommendations returns a Recommendations
func newRecommendations(c *AnalysisV1alpha1Client, namespace string) *recommendations {
	return &recommendations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the recommendation, and returns the corresponding recommendation object, and an error if there is any.
func (c *recommendations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Recommendation, err error) {
	result = &v1alpha1.Recommendation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("recommendations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Recommendations that match those selectors.
func (c *recommendations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RecommendationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RecommendationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("recommendations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested recommendations.
func (c *recommendations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("recommendations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a recommendation and creates it.  Returns the server's representation of the recommendation, and an error, if there is any.
func (c *recommendations) Create(ctx context.Context, recommendation *v1alpha1.Recommendation, opts v1.CreateOptions) (result *v1alpha1.Recommendation, err error) {
	result = &v1alpha1.Recommendation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("recommendations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(recommendation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a recommendation and updates it. Returns the server's representation of the recommendation, and an error, if there is any.
func (c *recommendations) Update(ctx context.Context, recommendation *v1alpha1.Recommendation, opts v1.UpdateOptions) (result *v1alpha1.Recommendation, err error) {
	result = &v1alpha1.Recommendation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("recommendations").
		Name(recommendation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(recommendation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *recommendations) UpdateStatus(ctx context.Context, recommendation *v1alpha1.Recommendation, opts v1.UpdateOptions) (result *v1alpha1.Recommendation, err error) {
	result = &v1alpha1.Recommendation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("recommendations").
		Name(recommendation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(recommendation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the recommendation and deletes it. Returns an error if one occurs.
func (c *recommendations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("recommendations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *recommendations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("recommendations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched recommendation.
func (c *recommendations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Recommendation, err error) {
	result = &v1alpha1.Recommendation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("recommendations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
