/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	schedulingv1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	scheme "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterNetworkTopologiesGetter has a method to return a ClusterNetworkTopologyInterface.
// A group's client should implement this interface.
type ClusterNetworkTopologiesGetter interface {
	ClusterNetworkTopologies() ClusterNetworkTopologyInterface
}

// ClusterNetworkTopologyInterface has methods to work with ClusterNetworkTopology resources.
type ClusterNetworkTopologyInterface interface {
	Create(ctx context.Context, clusterNetworkTopology *schedulingv1alpha1.ClusterNetworkTopology, opts v1.CreateOptions) (*schedulingv1alpha1.ClusterNetworkTopology, error)
	Update(ctx context.Context, clusterNetworkTopology *schedulingv1alpha1.ClusterNetworkTopology, opts v1.UpdateOptions) (*schedulingv1alpha1.ClusterNetworkTopology, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterNetworkTopology *schedulingv1alpha1.ClusterNetworkTopology, opts v1.UpdateOptions) (*schedulingv1alpha1.ClusterNetworkTopology, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*schedulingv1alpha1.ClusterNetworkTopology, error)
	List(ctx context.Context, opts v1.ListOptions) (*schedulingv1alpha1.ClusterNetworkTopologyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *schedulingv1alpha1.ClusterNetworkTopology, err error)
	ClusterNetworkTopologyExpansion
}

// clusterNetworkTopologies implements ClusterNetworkTopologyInterface
type clusterNetworkTopologies struct {
	*gentype.ClientWithList[*schedulingv1alpha1.ClusterNetworkTopology, *schedulingv1alpha1.ClusterNetworkTopologyList]
}

// newClusterNetworkTopologies returns a ClusterNetworkTopologies
func newClusterNetworkTopologies(c *SchedulingV1alpha1Client) *clusterNetworkTopologies {
	return &clusterNetworkTopologies{
		gentype.NewClientWithList[*schedulingv1alpha1.ClusterNetworkTopology, *schedulingv1alpha1.ClusterNetworkTopologyList](
			"clusternetworktopologies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *schedulingv1alpha1.ClusterNetworkTopology { return &schedulingv1alpha1.ClusterNetworkTopology{} },
			func() *schedulingv1alpha1.ClusterNetworkTopologyList {
				return &schedulingv1alpha1.ClusterNetworkTopologyList{}
			},
		),
	}
}
