/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	scheme "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ScheduleExplanationsGetter has a method to return a ScheduleExplanationInterface.
// A group's client should implement this interface.
type ScheduleExplanationsGetter interface {
	ScheduleExplanations(namespace string) ScheduleExplanationInterface
}

// ScheduleExplanationInterface has methods to work with ScheduleExplanation resources.
type ScheduleExplanationInterface interface {
	Create(ctx context.Context, scheduleExplanation *v1alpha1.ScheduleExplanation, opts v1.CreateOptions) (*v1alpha1.ScheduleExplanation, error)
	Update(ctx context.Context, scheduleExplanation *v1alpha1.ScheduleExplanation, opts v1.UpdateOptions) (*v1alpha1.ScheduleExplanation, error)
	UpdateStatus(ctx context.Context, scheduleExplanation *v1alpha1.ScheduleExplanation, opts v1.UpdateOptions) (*v1alpha1.ScheduleExplanation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ScheduleExplanation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ScheduleExplanationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ScheduleExplanation, err error)
	ScheduleExplanationExpansion
}

// scheduleExplanations implements ScheduleExplanationInterface
type scheduleExplanations struct {
	client rest.Interface
	ns     string
}

// newScheduleExplanations returns a ScheduleExplanations
func newScheduleExplanations(c *SchedulingV1alpha1Client, namespace string) *scheduleExplanations {
	return &scheduleExplanations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the scheduleExplanation, and returns the corresponding scheduleExplanation object, and an error if there is any.
func (c *scheduleExplanations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ScheduleExplanation, err error) {
	result = &v1alpha1.ScheduleExplanation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scheduleexplanations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ScheduleExplanations that match those selectors.
func (c *scheduleExplanations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ScheduleExplanationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ScheduleExplanationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scheduleexplanations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested scheduleExplanations.
func (c *scheduleExplanations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("scheduleexplanations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a scheduleExplanation and creates it.  Returns the server's representation of the scheduleExplanation, and an error, if there is any.
func (c *scheduleExplanations) Create(ctx context.Context, scheduleExplanation *v1alpha1.ScheduleExplanation, opts v1.CreateOptions) (result *v1alpha1.ScheduleExplanation, err error) {
	result = &v1alpha1.ScheduleExplanation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("scheduleexplanations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scheduleExplanation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a scheduleExplanation and updates it. Returns the server's representation of the scheduleExplanation, and an error, if there is any.
func (c *scheduleExplanations) Update(ctx context.Context, scheduleExplanation *v1alpha1.ScheduleExplanation, opts v1.UpdateOptions) (result *v1alpha1.ScheduleExplanation, err error) {
	result = &v1alpha1.ScheduleExplanation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scheduleexplanations").
		Name(scheduleExplanation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scheduleExplanation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *scheduleExplanations) UpdateStatus(ctx context.Context, scheduleExplanation *v1alpha1.ScheduleExplanation, opts v1.UpdateOptions) (result *v1alpha1.ScheduleExplanation, err error) {
	result = &v1alpha1.ScheduleExplanation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scheduleexplanations").
		Name(scheduleExplanation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scheduleExplanation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the scheduleExplanation and deletes it. Returns an error if one occurs.
func (c *scheduleExplanations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scheduleexplanations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *scheduleExplanations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scheduleexplanations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched scheduleExplanation.
func (c *scheduleExplanations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ScheduleExplanation, err error) {
	result = &v1alpha1.ScheduleExplanation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("scheduleexplanations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
