/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	configv1alpha1 "github.com/koordinator-sh/koordinator/apis/config/v1alpha1"
	scheme "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterColocationProfilesGetter has a method to return a ClusterColocationProfileInterface.
// A group's client should implement this interface.
type ClusterColocationProfilesGetter interface {
	ClusterColocationProfiles() ClusterColocationProfileInterface
}

// ClusterColocationProfileInterface has methods to work with ClusterColocationProfile resources.
type ClusterColocationProfileInterface interface {
	Create(ctx context.Context, clusterColocationProfile *configv1alpha1.ClusterColocationProfile, opts v1.CreateOptions) (*configv1alpha1.ClusterColocationProfile, error)
	Update(ctx context.Context, clusterColocationProfile *configv1alpha1.ClusterColocationProfile, opts v1.UpdateOptions) (*configv1alpha1.ClusterColocationProfile, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterColocationProfile *configv1alpha1.ClusterColocationProfile, opts v1.UpdateOptions) (*configv1alpha1.ClusterColocationProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*configv1alpha1.ClusterColocationProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*configv1alpha1.ClusterColocationProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *configv1alpha1.ClusterColocationProfile, err error)
	ClusterColocationProfileExpansion
}

// clusterColocationProfiles implements ClusterColocationProfileInterface
type clusterColocationProfiles struct {
	*gentype.ClientWithList[*configv1alpha1.ClusterColocationProfile, *configv1alpha1.ClusterColocationProfileList]
}

// newClusterColocationProfiles returns a ClusterColocationProfiles
func newClusterColocationProfiles(c *ConfigV1alpha1Client) *clusterColocationProfiles {
	return &clusterColocationProfiles{
		gentype.NewClientWithList[*configv1alpha1.ClusterColocationProfile, *configv1alpha1.ClusterColocationProfileList](
			"clustercolocationprofiles",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *configv1alpha1.ClusterColocationProfile { return &configv1alpha1.ClusterColocationProfile{} },
			func() *configv1alpha1.ClusterColocationProfileList {
				return &configv1alpha1.ClusterColocationProfileList{}
			},
		),
	}
}
