version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - depguard
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: Use corresponding 'os' or 'io' functions instead.
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - '-S1*'
        - '-ST1*'
        - '-QF1*'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA1019:'
    paths:
      - apis
      - pkg/client
      - vendor
      - test
      - pkg/util/httputil
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/koordinator-sh/koordinator
  exclusions:
    generated: lax
    paths:
      - apis
      - pkg/client
      - vendor
      - test
      - pkg/util/httputil
      - third_party$
      - builtin$
      - examples$
