project_name: koordinator-sh
env:
  - GIT_URL=https://github.com/koordinator-sh/koordinator
before:
  hooks:
    - go mod tidy
builds:
  - id: koord-runtime-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/koord-runtime-proxy
    binary: koord-runtime-proxy
    ldflags:
      - -s -w
      - -X github.com/koordinator-sh/koordinator/pkg/version.version={{ .Version }}
      - -X github.com/koordinator-sh/koordinator/pkg/version.buildDate={{ .Date }}
      - -X github.com/koordinator-sh/koordinator/pkg/version.gitCommit={{ .Commit }}
      - -X github.com/koordinator-sh/koordinator/pkg/version.gitTreeState=clean
archives:
  - id: koord-runtime-proxy
    format: binary
    builds:
      - koord-runtime-proxy
    replacements:
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^feat(deps):'
