# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project:
      # global coverage
      default:
        target: auto
        threshold: 2%
        flags:
          - unittests
        paths:
          - "pkg"
        # advanced settings
        if_ci_failed: error # success, failure, error, ignore
        if_no_uploads: error
        if_not_found: success # no commit found? still set a success
    patch:
      # diff coverage
      default:
        target: 70%
        flags:
          - unittests
        paths:
          - "pkg"
        if_ci_failed: error
        if_no_uploads: success
        if_not_found: success

ignore:
  - "**/*_generated.*"

github_checks:
  annotations: true
