# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project:
      # global coverage
      default:
        target: auto
        threshold: 2%
        flags:
          - unittests
        paths:
          - "pkg"
        if_ci_failed: error
        if_no_uploads: error
        if_not_found: success
    patch:
      # diff coverage
      default:
        target: 70%
        flags:
          - unittests
        paths:
          - "pkg"
        informational: true
        if_ci_failed: ignore
        if_no_uploads: success
        if_not_found: success

ignore:
  - "apis"
  - "pkg/client"
  - "**/*_generated.*"

github_checks:
  annotations: true
