apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    koord-app: koordlet
  name: koordlet
  namespace: system
spec:
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 20%
    type: RollingUpdate
  selector:
    matchLabels:
      koord-app: koordlet
  template:
    metadata:
      labels:
        koord-app: koordlet
        runtimeproxy.koordinator.sh/skip-hookserver: "true"
    spec:
      containers:
        - args:
            - -cgroup-root-dir=/host-cgroup/
            - -feature-gates=AllAlpha=true,AllBeta=true
            - -runtime-hooks-network=unix
            - -runtime-hooks-addr=/host-var-run-koordlet/koordlet.sock
            - -runtime-hooks-host-endpoint=/var/run/koordlet//koordlet.sock
            - --logtostderr=true
            - --v=4
          command:
            - /koordlet
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: koordlet:latest
          imagePullPolicy: Always
          name: koordlet
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: "0"
              memory: "0"
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - mountPath: /etc/localtime
              name: host-time
              readOnly: true
            - mountPath: /host-cgroup/
              name: host-cgroup-root
            - mountPath: /host-sys-fs/
              mountPropagation: Bidirectional
              name: host-sys-fs
            - mountPath: /host-var-run/
              name: host-var-run
              readOnly: true
            - mountPath: /host-var-run-koordlet/
              mountPropagation: Bidirectional
              name: host-var-run-koordlet
            - mountPath: /host-sys/
              name: host-sys
              readOnly: true
            - mountPath: /etc/kubernetes/
              name: host-kubernetes
              readOnly: true
            - mountPath: /host-etc-hookserver/
              mountPropagation: Bidirectional
              name: host-etc-hookserver
            - mountPath: /var/lib/kubelet
              name: host-kubelet-rootdir
              readOnly: true
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      serviceAccountName: koordlet
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
        - hostPath:
            path: /sys/fs/cgroup/
            type: ""
          name: host-cgroup-root
        - hostPath:
            path: /sys/fs/
            type: ""
          name: host-sys-fs
        - hostPath:
            path: /var/run/
            type: ""
          name: host-var-run
        - hostPath:
            path: /var/run/koordlet/
            type: DirectoryOrCreate
          name: host-var-run-koordlet
        - hostPath:
            path: /sys/
            type: ""
          name: host-sys
        - hostPath:
            path: /etc/kubernetes/
            type: ""
          name: host-kubernetes
        - hostPath:
            path: /etc/runtime/hookserver.d/
            type: ""
          name: host-etc-hookserver
        - hostPath:
            path: /var/lib/kubelet/
            type: ""
          name: host-kubelet-rootdir
