resources:
  - manager.yaml
  - scheduler.yaml
  - scheduler-config.yaml
  - descheduler.yaml
  - descheduler-config.yaml
  - koordlet.yaml
  - koord-batch.yaml
  - koord-free.yaml
  - koord-mid.yaml
  - koord-prod.yaml
  - slo-controller-config.yaml

generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: descheduler
    newName: registry.cn-hangzhou.aliyuncs.com/koordinator-sh/koord-descheduler
    newTag: latest
  - name: koordlet
    newName: registry.cn-hangzhou.aliyuncs.com/koordinator-sh/koordlet
    newTag: latest
  - name: manager
    newName: registry.cn-hangzhou.aliyuncs.com/koordinator-sh/koord-manager
    newTag: latest
  - name: scheduler
    newName: registry.cn-hangzhou.aliyuncs.com/koordinator-sh/koord-scheduler
    newTag: latest
