//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 Copyright 2022 The Koordinator Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadAwareSchedulingArgs) DeepCopyInto(out *LoadAwareSchedulingArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.FilterExpiredNodeMetrics != nil {
		in, out := &in.FilterExpiredNodeMetrics, &out.FilterExpiredNodeMetrics
		*out = new(bool)
		**out = **in
	}
	if in.NodeMetricExpirationSeconds != nil {
		in, out := &in.NodeMetricExpirationSeconds, &out.NodeMetricExpirationSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ResourceWeights != nil {
		in, out := &in.ResourceWeights, &out.ResourceWeights
		*out = make(map[v1.ResourceName]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UsageThresholds != nil {
		in, out := &in.UsageThresholds, &out.UsageThresholds
		*out = make(map[v1.ResourceName]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EstimatedScalingFactors != nil {
		in, out := &in.EstimatedScalingFactors, &out.EstimatedScalingFactors
		*out = make(map[v1.ResourceName]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadAwareSchedulingArgs.
func (in *LoadAwareSchedulingArgs) DeepCopy() *LoadAwareSchedulingArgs {
	if in == nil {
		return nil
	}
	out := new(LoadAwareSchedulingArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadAwareSchedulingArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
