//go:build !ignore_autogenerated

/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopology) DeepCopyInto(out *ClusterNetworkTopology) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopology.
func (in *ClusterNetworkTopology) DeepCopy() *ClusterNetworkTopology {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterNetworkTopology) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopologyDetailStatus) DeepCopyInto(out *ClusterNetworkTopologyDetailStatus) {
	*out = *in
	out.TopologyInfo = in.TopologyInfo
	if in.ParentTopologyInfo != nil {
		in, out := &in.ParentTopologyInfo, &out.ParentTopologyInfo
		*out = new(TopologyInfo)
		**out = **in
	}
	if in.ChildTopologyNames != nil {
		in, out := &in.ChildTopologyNames, &out.ChildTopologyNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopologyDetailStatus.
func (in *ClusterNetworkTopologyDetailStatus) DeepCopy() *ClusterNetworkTopologyDetailStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopologyDetailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopologyList) DeepCopyInto(out *ClusterNetworkTopologyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterNetworkTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopologyList.
func (in *ClusterNetworkTopologyList) DeepCopy() *ClusterNetworkTopologyList {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopologyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterNetworkTopologyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopologySpec) DeepCopyInto(out *ClusterNetworkTopologySpec) {
	*out = *in
	if in.NetworkTopologySpec != nil {
		in, out := &in.NetworkTopologySpec, &out.NetworkTopologySpec
		*out = make([]NetworkTopologySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopologySpec.
func (in *ClusterNetworkTopologySpec) DeepCopy() *ClusterNetworkTopologySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopologyStatus) DeepCopyInto(out *ClusterNetworkTopologyStatus) {
	*out = *in
	if in.DetailStatus != nil {
		in, out := &in.DetailStatus, &out.DetailStatus
		*out = make([]*ClusterNetworkTopologyDetailStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ClusterNetworkTopologyDetailStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopologyStatus.
func (in *ClusterNetworkTopologyStatus) DeepCopy() *ClusterNetworkTopologyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopologyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Device) DeepCopyInto(out *Device) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Device.
func (in *Device) DeepCopy() *Device {
	if in == nil {
		return nil
	}
	out := new(Device)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Device) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAllocation) DeepCopyInto(out *DeviceAllocation) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]DeviceAllocationItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAllocation.
func (in *DeviceAllocation) DeepCopy() *DeviceAllocation {
	if in == nil {
		return nil
	}
	out := new(DeviceAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAllocationItem) DeepCopyInto(out *DeviceAllocationItem) {
	*out = *in
	if in.Minors != nil {
		in, out := &in.Minors, &out.Minors
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAllocationItem.
func (in *DeviceAllocationItem) DeepCopy() *DeviceAllocationItem {
	if in == nil {
		return nil
	}
	out := new(DeviceAllocationItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceInfo) DeepCopyInto(out *DeviceInfo) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Minor != nil {
		in, out := &in.Minor, &out.Minor
		*out = new(int32)
		**out = **in
	}
	if in.ModuleID != nil {
		in, out := &in.ModuleID, &out.ModuleID
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(DeviceTopology)
		**out = **in
	}
	if in.VFGroups != nil {
		in, out := &in.VFGroups, &out.VFGroups
		*out = make([]VirtualFunctionGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceInfo.
func (in *DeviceInfo) DeepCopy() *DeviceInfo {
	if in == nil {
		return nil
	}
	out := new(DeviceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceList) DeepCopyInto(out *DeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Device, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceList.
func (in *DeviceList) DeepCopy() *DeviceList {
	if in == nil {
		return nil
	}
	out := new(DeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSpec) DeepCopyInto(out *DeviceSpec) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]DeviceInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSpec.
func (in *DeviceSpec) DeepCopy() *DeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]DeviceAllocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceTopology) DeepCopyInto(out *DeviceTopology) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceTopology.
func (in *DeviceTopology) DeepCopy() *DeviceTopology {
	if in == nil {
		return nil
	}
	out := new(DeviceTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkTopologySpec) DeepCopyInto(out *NetworkTopologySpec) {
	*out = *in
	if in.LabelKey != nil {
		in, out := &in.LabelKey, &out.LabelKey
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkTopologySpec.
func (in *NetworkTopologySpec) DeepCopy() *NetworkTopologySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeFailedDetail) DeepCopyInto(out *NodeFailedDetail) {
	*out = *in
	if in.NominatedPods != nil {
		in, out := &in.NominatedPods, &out.NominatedPods
		*out = make([]NamespacedName, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeFailedDetail.
func (in *NodeFailedDetail) DeepCopy() *NodeFailedDetail {
	if in == nil {
		return nil
	}
	out := new(NodeFailedDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLevelExplanations) DeepCopyInto(out *NodeLevelExplanations) {
	*out = *in
	if in.FeasibleSchedulingResult != nil {
		in, out := &in.FeasibleSchedulingResult, &out.FeasibleSchedulingResult
		*out = make([]SchedulingResult, len(*in))
		copy(*out, *in)
	}
	if in.NodeFailedDetails != nil {
		in, out := &in.NodeFailedDetails, &out.NodeFailedDetails
		*out = make([]NodeFailedDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLevelExplanations.
func (in *NodeLevelExplanations) DeepCopy() *NodeLevelExplanations {
	if in == nil {
		return nil
	}
	out := new(NodeLevelExplanations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePossibleVictim) DeepCopyInto(out *NodePossibleVictim) {
	*out = *in
	if in.PossibleVictims != nil {
		in, out := &in.PossibleVictims, &out.PossibleVictims
		*out = make([]PossibleVictim, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePossibleVictim.
func (in *NodePossibleVictim) DeepCopy() *NodePossibleVictim {
	if in == nil {
		return nil
	}
	out := new(NodePossibleVictim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrateReservationOptions) DeepCopyInto(out *PodMigrateReservationOptions) {
	*out = *in
	if in.ReservationRef != nil {
		in, out := &in.ReservationRef, &out.ReservationRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(ReservationTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PreemptionOptions != nil {
		in, out := &in.PreemptionOptions, &out.PreemptionOptions
		*out = new(PodMigrationJobPreemptionOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrateReservationOptions.
func (in *PodMigrateReservationOptions) DeepCopy() *PodMigrateReservationOptions {
	if in == nil {
		return nil
	}
	out := new(PodMigrateReservationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationJob) DeepCopyInto(out *PodMigrationJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationJob.
func (in *PodMigrationJob) DeepCopy() *PodMigrationJob {
	if in == nil {
		return nil
	}
	out := new(PodMigrationJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodMigrationJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationJobCondition) DeepCopyInto(out *PodMigrationJobCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationJobCondition.
func (in *PodMigrationJobCondition) DeepCopy() *PodMigrationJobCondition {
	if in == nil {
		return nil
	}
	out := new(PodMigrationJobCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationJobList) DeepCopyInto(out *PodMigrationJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodMigrationJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationJobList.
func (in *PodMigrationJobList) DeepCopy() *PodMigrationJobList {
	if in == nil {
		return nil
	}
	out := new(PodMigrationJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodMigrationJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationJobPreemptedReservation) DeepCopyInto(out *PodMigrationJobPreemptedReservation) {
	*out = *in
	if in.PreemptedPodRef != nil {
		in, out := &in.PreemptedPodRef, &out.PreemptedPodRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.PodsRef != nil {
		in, out := &in.PodsRef, &out.PodsRef
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationJobPreemptedReservation.
func (in *PodMigrationJobPreemptedReservation) DeepCopy() *PodMigrationJobPreemptedReservation {
	if in == nil {
		return nil
	}
	out := new(PodMigrationJobPreemptedReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationJobPreemptionOptions) DeepCopyInto(out *PodMigrationJobPreemptionOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationJobPreemptionOptions.
func (in *PodMigrationJobPreemptionOptions) DeepCopy() *PodMigrationJobPreemptionOptions {
	if in == nil {
		return nil
	}
	out := new(PodMigrationJobPreemptionOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationJobSpec) DeepCopyInto(out *PodMigrationJobSpec) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.ReservationOptions != nil {
		in, out := &in.ReservationOptions, &out.ReservationOptions
		*out = new(PodMigrateReservationOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.DeleteOptions != nil {
		in, out := &in.DeleteOptions, &out.DeleteOptions
		*out = new(metav1.DeleteOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationJobSpec.
func (in *PodMigrationJobSpec) DeepCopy() *PodMigrationJobSpec {
	if in == nil {
		return nil
	}
	out := new(PodMigrationJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMigrationJobStatus) DeepCopyInto(out *PodMigrationJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PodMigrationJobCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.PreemptedPodsRef != nil {
		in, out := &in.PreemptedPodsRef, &out.PreemptedPodsRef
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.PreemptedPodsReservations != nil {
		in, out := &in.PreemptedPodsReservations, &out.PreemptedPodsReservations
		*out = make([]PodMigrationJobPreemptedReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMigrationJobStatus.
func (in *PodMigrationJobStatus) DeepCopy() *PodMigrationJobStatus {
	if in == nil {
		return nil
	}
	out := new(PodMigrationJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PossibleVictim) DeepCopyInto(out *PossibleVictim) {
	*out = *in
	out.NamespacedName = in.NamespacedName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PossibleVictim.
func (in *PossibleVictim) DeepCopy() *PossibleVictim {
	if in == nil {
		return nil
	}
	out := new(PossibleVictim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreAllocationPolicy) DeepCopyInto(out *PreAllocationPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreAllocationPolicy.
func (in *PreAllocationPolicy) DeepCopy() *PreAllocationPolicy {
	if in == nil {
		return nil
	}
	out := new(PreAllocationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reservation) DeepCopyInto(out *Reservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reservation.
func (in *Reservation) DeepCopy() *Reservation {
	if in == nil {
		return nil
	}
	out := new(Reservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Reservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationCondition) DeepCopyInto(out *ReservationCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationCondition.
func (in *ReservationCondition) DeepCopy() *ReservationCondition {
	if in == nil {
		return nil
	}
	out := new(ReservationCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationControllerReference) DeepCopyInto(out *ReservationControllerReference) {
	*out = *in
	in.OwnerReference.DeepCopyInto(&out.OwnerReference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationControllerReference.
func (in *ReservationControllerReference) DeepCopy() *ReservationControllerReference {
	if in == nil {
		return nil
	}
	out := new(ReservationControllerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationList) DeepCopyInto(out *ReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Reservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationList.
func (in *ReservationList) DeepCopy() *ReservationList {
	if in == nil {
		return nil
	}
	out := new(ReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationOwner) DeepCopyInto(out *ReservationOwner) {
	*out = *in
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(ReservationControllerReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationOwner.
func (in *ReservationOwner) DeepCopy() *ReservationOwner {
	if in == nil {
		return nil
	}
	out := new(ReservationOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationSpec) DeepCopyInto(out *ReservationSpec) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]ReservationOwner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = (*in).DeepCopy()
	}
	if in.AllocateOnce != nil {
		in, out := &in.AllocateOnce, &out.AllocateOnce
		*out = new(bool)
		**out = **in
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]v1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreAllocationPolicy != nil {
		in, out := &in.PreAllocationPolicy, &out.PreAllocationPolicy
		*out = new(PreAllocationPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationSpec.
func (in *ReservationSpec) DeepCopy() *ReservationSpec {
	if in == nil {
		return nil
	}
	out := new(ReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationStatus) DeepCopyInto(out *ReservationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ReservationCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentOwners != nil {
		in, out := &in.CurrentOwners, &out.CurrentOwners
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Allocatable != nil {
		in, out := &in.Allocatable, &out.Allocatable
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Allocated != nil {
		in, out := &in.Allocated, &out.Allocated
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationStatus.
func (in *ReservationStatus) DeepCopy() *ReservationStatus {
	if in == nil {
		return nil
	}
	out := new(ReservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationTemplateSpec) DeepCopyInto(out *ReservationTemplateSpec) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationTemplateSpec.
func (in *ReservationTemplateSpec) DeepCopy() *ReservationTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ReservationTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleExplanation) DeepCopyInto(out *ScheduleExplanation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleExplanation.
func (in *ScheduleExplanation) DeepCopy() *ScheduleExplanation {
	if in == nil {
		return nil
	}
	out := new(ScheduleExplanation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduleExplanation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleExplanationList) DeepCopyInto(out *ScheduleExplanationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScheduleExplanation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleExplanationList.
func (in *ScheduleExplanationList) DeepCopy() *ScheduleExplanationList {
	if in == nil {
		return nil
	}
	out := new(ScheduleExplanationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduleExplanationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleExplanationSpec) DeepCopyInto(out *ScheduleExplanationSpec) {
	*out = *in
	if in.QuestionObjectReference != nil {
		in, out := &in.QuestionObjectReference, &out.QuestionObjectReference
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.QuestionObjectTemplate != nil {
		in, out := &in.QuestionObjectTemplate, &out.QuestionObjectTemplate
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleExplanationSpec.
func (in *ScheduleExplanationSpec) DeepCopy() *ScheduleExplanationSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduleExplanationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleExplanationStatus) DeepCopyInto(out *ScheduleExplanationStatus) {
	*out = *in
	if in.DetailedExplanation != nil {
		in, out := &in.DetailedExplanation, &out.DetailedExplanation
		*out = make([]*TopologyDomainLevelExplanation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TopologyDomainLevelExplanation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleExplanationStatus.
func (in *ScheduleExplanationStatus) DeepCopy() *ScheduleExplanationStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduleExplanationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingResult) DeepCopyInto(out *SchedulingResult) {
	*out = *in
	out.NamespacedName = in.NamespacedName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingResult.
func (in *SchedulingResult) DeepCopy() *SchedulingResult {
	if in == nil {
		return nil
	}
	out := new(SchedulingResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyDomainLevelExplanation) DeepCopyInto(out *TopologyDomainLevelExplanation) {
	*out = *in
	in.ScheduleExplanation.DeepCopyInto(&out.ScheduleExplanation)
	if in.NodePossibleVictims != nil {
		in, out := &in.NodePossibleVictims, &out.NodePossibleVictims
		*out = make([]NodePossibleVictim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PreemptExplanation.DeepCopyInto(&out.PreemptExplanation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyDomainLevelExplanation.
func (in *TopologyDomainLevelExplanation) DeepCopy() *TopologyDomainLevelExplanation {
	if in == nil {
		return nil
	}
	out := new(TopologyDomainLevelExplanation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyInfo) DeepCopyInto(out *TopologyInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyInfo.
func (in *TopologyInfo) DeepCopy() *TopologyInfo {
	if in == nil {
		return nil
	}
	out := new(TopologyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualFunction) DeepCopyInto(out *VirtualFunction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualFunction.
func (in *VirtualFunction) DeepCopy() *VirtualFunction {
	if in == nil {
		return nil
	}
	out := new(VirtualFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualFunctionGroup) DeepCopyInto(out *VirtualFunctionGroup) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VFs != nil {
		in, out := &in.VFs, &out.VFs
		*out = make([]VirtualFunction, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualFunctionGroup.
func (in *VirtualFunctionGroup) DeepCopy() *VirtualFunctionGroup {
	if in == nil {
		return nil
	}
	out := new(VirtualFunctionGroup)
	in.DeepCopyInto(out)
	return out
}
