/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	schedulingv1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ScheduleExplanationLister helps list ScheduleExplanations.
// All objects returned here must be treated as read-only.
type ScheduleExplanationLister interface {
	// List lists all ScheduleExplanations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1alpha1.ScheduleExplanation, err error)
	// ScheduleExplanations returns an object that can list and get ScheduleExplanations.
	ScheduleExplanations(namespace string) ScheduleExplanationNamespaceLister
	ScheduleExplanationListerExpansion
}

// scheduleExplanationLister implements the ScheduleExplanationLister interface.
type scheduleExplanationLister struct {
	listers.ResourceIndexer[*schedulingv1alpha1.ScheduleExplanation]
}

// NewScheduleExplanationLister returns a new ScheduleExplanationLister.
func NewScheduleExplanationLister(indexer cache.Indexer) ScheduleExplanationLister {
	return &scheduleExplanationLister{listers.New[*schedulingv1alpha1.ScheduleExplanation](indexer, schedulingv1alpha1.Resource("scheduleexplanation"))}
}

// ScheduleExplanations returns an object that can list and get ScheduleExplanations.
func (s *scheduleExplanationLister) ScheduleExplanations(namespace string) ScheduleExplanationNamespaceLister {
	return scheduleExplanationNamespaceLister{listers.NewNamespaced[*schedulingv1alpha1.ScheduleExplanation](s.ResourceIndexer, namespace)}
}

// ScheduleExplanationNamespaceLister helps list and get ScheduleExplanations.
// All objects returned here must be treated as read-only.
type ScheduleExplanationNamespaceLister interface {
	// List lists all ScheduleExplanations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1alpha1.ScheduleExplanation, err error)
	// Get retrieves the ScheduleExplanation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*schedulingv1alpha1.ScheduleExplanation, error)
	ScheduleExplanationNamespaceListerExpansion
}

// scheduleExplanationNamespaceLister implements the ScheduleExplanationNamespaceLister
// interface.
type scheduleExplanationNamespaceLister struct {
	listers.ResourceIndexer[*schedulingv1alpha1.ScheduleExplanation]
}
