//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.3
// source: yarn_server_resourcemanager_service_protos.proto

package server

import (
	hadoopyarn "github.com/koordinator-sh/koordinator/pkg/yarn/apis/proto/hadoopyarn"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecommissionTypeProto int32

const (
	DecommissionTypeProto_NORMAL   DecommissionTypeProto = 1
	DecommissionTypeProto_GRACEFUL DecommissionTypeProto = 2
	DecommissionTypeProto_FORCEFUL DecommissionTypeProto = 3
)

// Enum value maps for DecommissionTypeProto.
var (
	DecommissionTypeProto_name = map[int32]string{
		1: "NORMAL",
		2: "GRACEFUL",
		3: "FORCEFUL",
	}
	DecommissionTypeProto_value = map[string]int32{
		"NORMAL":   1,
		"GRACEFUL": 2,
		"FORCEFUL": 3,
	}
)

func (x DecommissionTypeProto) Enum() *DecommissionTypeProto {
	p := new(DecommissionTypeProto)
	*p = x
	return p
}

func (x DecommissionTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecommissionTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_yarn_server_resourcemanager_service_protos_proto_enumTypes[0].Descriptor()
}

func (DecommissionTypeProto) Type() protoreflect.EnumType {
	return &file_yarn_server_resourcemanager_service_protos_proto_enumTypes[0]
}

func (x DecommissionTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DecommissionTypeProto) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DecommissionTypeProto(num)
	return nil
}

// Deprecated: Use DecommissionTypeProto.Descriptor instead.
func (DecommissionTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{0}
}

type AttributeMappingOperationTypeProto int32

const (
	AttributeMappingOperationTypeProto_REPLACE AttributeMappingOperationTypeProto = 1
	AttributeMappingOperationTypeProto_ADD     AttributeMappingOperationTypeProto = 2
	AttributeMappingOperationTypeProto_REMOVE  AttributeMappingOperationTypeProto = 3
)

// Enum value maps for AttributeMappingOperationTypeProto.
var (
	AttributeMappingOperationTypeProto_name = map[int32]string{
		1: "REPLACE",
		2: "ADD",
		3: "REMOVE",
	}
	AttributeMappingOperationTypeProto_value = map[string]int32{
		"REPLACE": 1,
		"ADD":     2,
		"REMOVE":  3,
	}
)

func (x AttributeMappingOperationTypeProto) Enum() *AttributeMappingOperationTypeProto {
	p := new(AttributeMappingOperationTypeProto)
	*p = x
	return p
}

func (x AttributeMappingOperationTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeMappingOperationTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_yarn_server_resourcemanager_service_protos_proto_enumTypes[1].Descriptor()
}

func (AttributeMappingOperationTypeProto) Type() protoreflect.EnumType {
	return &file_yarn_server_resourcemanager_service_protos_proto_enumTypes[1]
}

func (x AttributeMappingOperationTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AttributeMappingOperationTypeProto) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AttributeMappingOperationTypeProto(num)
	return nil
}

// Deprecated: Use AttributeMappingOperationTypeProto.Descriptor instead.
func (AttributeMappingOperationTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{1}
}

type RefreshQueuesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshQueuesRequestProto) Reset() {
	*x = RefreshQueuesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshQueuesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshQueuesRequestProto) ProtoMessage() {}

func (x *RefreshQueuesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshQueuesRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshQueuesRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{0}
}

type RefreshQueuesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshQueuesResponseProto) Reset() {
	*x = RefreshQueuesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshQueuesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshQueuesResponseProto) ProtoMessage() {}

func (x *RefreshQueuesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshQueuesResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshQueuesResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{1}
}

type RefreshNodesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DecommissionType    *DecommissionTypeProto `protobuf:"varint,1,opt,name=decommissionType,enum=hadoop.yarn.DecommissionTypeProto,def=1" json:"decommissionType,omitempty"`
	DecommissionTimeout *int32                 `protobuf:"varint,2,opt,name=decommissionTimeout" json:"decommissionTimeout,omitempty"`
}

// Default values for RefreshNodesRequestProto fields.
const (
	Default_RefreshNodesRequestProto_DecommissionType = DecommissionTypeProto_NORMAL
)

func (x *RefreshNodesRequestProto) Reset() {
	*x = RefreshNodesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNodesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNodesRequestProto) ProtoMessage() {}

func (x *RefreshNodesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNodesRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshNodesRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshNodesRequestProto) GetDecommissionType() DecommissionTypeProto {
	if x != nil && x.DecommissionType != nil {
		return *x.DecommissionType
	}
	return Default_RefreshNodesRequestProto_DecommissionType
}

func (x *RefreshNodesRequestProto) GetDecommissionTimeout() int32 {
	if x != nil && x.DecommissionTimeout != nil {
		return *x.DecommissionTimeout
	}
	return 0
}

type RefreshNodesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshNodesResponseProto) Reset() {
	*x = RefreshNodesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNodesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNodesResponseProto) ProtoMessage() {}

func (x *RefreshNodesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNodesResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshNodesResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{3}
}

type RefreshSuperUserGroupsConfigurationRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshSuperUserGroupsConfigurationRequestProto) Reset() {
	*x = RefreshSuperUserGroupsConfigurationRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshSuperUserGroupsConfigurationRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSuperUserGroupsConfigurationRequestProto) ProtoMessage() {}

func (x *RefreshSuperUserGroupsConfigurationRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSuperUserGroupsConfigurationRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshSuperUserGroupsConfigurationRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{4}
}

type RefreshSuperUserGroupsConfigurationResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshSuperUserGroupsConfigurationResponseProto) Reset() {
	*x = RefreshSuperUserGroupsConfigurationResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshSuperUserGroupsConfigurationResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSuperUserGroupsConfigurationResponseProto) ProtoMessage() {}

func (x *RefreshSuperUserGroupsConfigurationResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSuperUserGroupsConfigurationResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshSuperUserGroupsConfigurationResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{5}
}

type RefreshUserToGroupsMappingsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshUserToGroupsMappingsRequestProto) Reset() {
	*x = RefreshUserToGroupsMappingsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshUserToGroupsMappingsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUserToGroupsMappingsRequestProto) ProtoMessage() {}

func (x *RefreshUserToGroupsMappingsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUserToGroupsMappingsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshUserToGroupsMappingsRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{6}
}

type RefreshUserToGroupsMappingsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshUserToGroupsMappingsResponseProto) Reset() {
	*x = RefreshUserToGroupsMappingsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshUserToGroupsMappingsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUserToGroupsMappingsResponseProto) ProtoMessage() {}

func (x *RefreshUserToGroupsMappingsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUserToGroupsMappingsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshUserToGroupsMappingsResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{7}
}

type RefreshAdminAclsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshAdminAclsRequestProto) Reset() {
	*x = RefreshAdminAclsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAdminAclsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAdminAclsRequestProto) ProtoMessage() {}

func (x *RefreshAdminAclsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAdminAclsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshAdminAclsRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{8}
}

type RefreshAdminAclsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshAdminAclsResponseProto) Reset() {
	*x = RefreshAdminAclsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAdminAclsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAdminAclsResponseProto) ProtoMessage() {}

func (x *RefreshAdminAclsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAdminAclsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshAdminAclsResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{9}
}

type RefreshServiceAclsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshServiceAclsRequestProto) Reset() {
	*x = RefreshServiceAclsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshServiceAclsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshServiceAclsRequestProto) ProtoMessage() {}

func (x *RefreshServiceAclsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshServiceAclsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshServiceAclsRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{10}
}

type RefreshServiceAclsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshServiceAclsResponseProto) Reset() {
	*x = RefreshServiceAclsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshServiceAclsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshServiceAclsResponseProto) ProtoMessage() {}

func (x *RefreshServiceAclsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshServiceAclsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshServiceAclsResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{11}
}

type GetGroupsForUserRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
}

func (x *GetGroupsForUserRequestProto) Reset() {
	*x = GetGroupsForUserRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupsForUserRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsForUserRequestProto) ProtoMessage() {}

func (x *GetGroupsForUserRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsForUserRequestProto.ProtoReflect.Descriptor instead.
func (*GetGroupsForUserRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{12}
}

func (x *GetGroupsForUserRequestProto) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

type GetGroupsForUserResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []string `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
}

func (x *GetGroupsForUserResponseProto) Reset() {
	*x = GetGroupsForUserResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupsForUserResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsForUserResponseProto) ProtoMessage() {}

func (x *GetGroupsForUserResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsForUserResponseProto.ProtoReflect.Descriptor instead.
func (*GetGroupsForUserResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{13}
}

func (x *GetGroupsForUserResponseProto) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type UpdateNodeResourceRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeResourceMap []*hadoopyarn.NodeResourceMapProto `protobuf:"bytes,1,rep,name=node_resource_map,json=nodeResourceMap" json:"node_resource_map,omitempty"`
}

func (x *UpdateNodeResourceRequestProto) Reset() {
	*x = UpdateNodeResourceRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNodeResourceRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeResourceRequestProto) ProtoMessage() {}

func (x *UpdateNodeResourceRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeResourceRequestProto.ProtoReflect.Descriptor instead.
func (*UpdateNodeResourceRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateNodeResourceRequestProto) GetNodeResourceMap() []*hadoopyarn.NodeResourceMapProto {
	if x != nil {
		return x.NodeResourceMap
	}
	return nil
}

type UpdateNodeResourceResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateNodeResourceResponseProto) Reset() {
	*x = UpdateNodeResourceResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNodeResourceResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeResourceResponseProto) ProtoMessage() {}

func (x *UpdateNodeResourceResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeResourceResponseProto.ProtoReflect.Descriptor instead.
func (*UpdateNodeResourceResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{15}
}

type RefreshNodesResourcesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshNodesResourcesRequestProto) Reset() {
	*x = RefreshNodesResourcesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNodesResourcesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNodesResourcesRequestProto) ProtoMessage() {}

func (x *RefreshNodesResourcesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNodesResourcesRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshNodesResourcesRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{16}
}

type RefreshNodesResourcesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshNodesResourcesResponseProto) Reset() {
	*x = RefreshNodesResourcesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNodesResourcesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNodesResourcesResponseProto) ProtoMessage() {}

func (x *RefreshNodesResourcesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNodesResourcesResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshNodesResourcesResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{17}
}

type AddToClusterNodeLabelsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeprecatedNodeLabels []string                     `protobuf:"bytes,1,rep,name=deprecatedNodeLabels" json:"deprecatedNodeLabels,omitempty"`
	NodeLabels           []*hadoopyarn.NodeLabelProto `protobuf:"bytes,2,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
}

func (x *AddToClusterNodeLabelsRequestProto) Reset() {
	*x = AddToClusterNodeLabelsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToClusterNodeLabelsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToClusterNodeLabelsRequestProto) ProtoMessage() {}

func (x *AddToClusterNodeLabelsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToClusterNodeLabelsRequestProto.ProtoReflect.Descriptor instead.
func (*AddToClusterNodeLabelsRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{18}
}

func (x *AddToClusterNodeLabelsRequestProto) GetDeprecatedNodeLabels() []string {
	if x != nil {
		return x.DeprecatedNodeLabels
	}
	return nil
}

func (x *AddToClusterNodeLabelsRequestProto) GetNodeLabels() []*hadoopyarn.NodeLabelProto {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

type AddToClusterNodeLabelsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddToClusterNodeLabelsResponseProto) Reset() {
	*x = AddToClusterNodeLabelsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToClusterNodeLabelsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToClusterNodeLabelsResponseProto) ProtoMessage() {}

func (x *AddToClusterNodeLabelsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToClusterNodeLabelsResponseProto.ProtoReflect.Descriptor instead.
func (*AddToClusterNodeLabelsResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{19}
}

type RemoveFromClusterNodeLabelsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeLabels []string `protobuf:"bytes,1,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
}

func (x *RemoveFromClusterNodeLabelsRequestProto) Reset() {
	*x = RemoveFromClusterNodeLabelsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromClusterNodeLabelsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromClusterNodeLabelsRequestProto) ProtoMessage() {}

func (x *RemoveFromClusterNodeLabelsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromClusterNodeLabelsRequestProto.ProtoReflect.Descriptor instead.
func (*RemoveFromClusterNodeLabelsRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveFromClusterNodeLabelsRequestProto) GetNodeLabels() []string {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

type RemoveFromClusterNodeLabelsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveFromClusterNodeLabelsResponseProto) Reset() {
	*x = RemoveFromClusterNodeLabelsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromClusterNodeLabelsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromClusterNodeLabelsResponseProto) ProtoMessage() {}

func (x *RemoveFromClusterNodeLabelsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromClusterNodeLabelsResponseProto.ProtoReflect.Descriptor instead.
func (*RemoveFromClusterNodeLabelsResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{21}
}

type ReplaceLabelsOnNodeRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeToLabels       []*hadoopyarn.NodeIdToLabelsProto `protobuf:"bytes,1,rep,name=nodeToLabels" json:"nodeToLabels,omitempty"`
	FailOnUnknownNodes *bool                             `protobuf:"varint,2,opt,name=failOnUnknownNodes" json:"failOnUnknownNodes,omitempty"`
}

func (x *ReplaceLabelsOnNodeRequestProto) Reset() {
	*x = ReplaceLabelsOnNodeRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceLabelsOnNodeRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceLabelsOnNodeRequestProto) ProtoMessage() {}

func (x *ReplaceLabelsOnNodeRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceLabelsOnNodeRequestProto.ProtoReflect.Descriptor instead.
func (*ReplaceLabelsOnNodeRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{22}
}

func (x *ReplaceLabelsOnNodeRequestProto) GetNodeToLabels() []*hadoopyarn.NodeIdToLabelsProto {
	if x != nil {
		return x.NodeToLabels
	}
	return nil
}

func (x *ReplaceLabelsOnNodeRequestProto) GetFailOnUnknownNodes() bool {
	if x != nil && x.FailOnUnknownNodes != nil {
		return *x.FailOnUnknownNodes
	}
	return false
}

type ReplaceLabelsOnNodeResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReplaceLabelsOnNodeResponseProto) Reset() {
	*x = ReplaceLabelsOnNodeResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceLabelsOnNodeResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceLabelsOnNodeResponseProto) ProtoMessage() {}

func (x *ReplaceLabelsOnNodeResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceLabelsOnNodeResponseProto.ProtoReflect.Descriptor instead.
func (*ReplaceLabelsOnNodeResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{23}
}

type UpdateNodeLabelsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateNodeLabelsResponseProto) Reset() {
	*x = UpdateNodeLabelsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNodeLabelsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeLabelsResponseProto) ProtoMessage() {}

func (x *UpdateNodeLabelsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeLabelsResponseProto.ProtoReflect.Descriptor instead.
func (*UpdateNodeLabelsResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{24}
}

type CheckForDecommissioningNodesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckForDecommissioningNodesRequestProto) Reset() {
	*x = CheckForDecommissioningNodesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckForDecommissioningNodesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForDecommissioningNodesRequestProto) ProtoMessage() {}

func (x *CheckForDecommissioningNodesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForDecommissioningNodesRequestProto.ProtoReflect.Descriptor instead.
func (*CheckForDecommissioningNodesRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{25}
}

type CheckForDecommissioningNodesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DecommissioningNodes []*hadoopyarn.NodeIdProto `protobuf:"bytes,1,rep,name=decommissioningNodes" json:"decommissioningNodes,omitempty"`
}

func (x *CheckForDecommissioningNodesResponseProto) Reset() {
	*x = CheckForDecommissioningNodesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckForDecommissioningNodesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForDecommissioningNodesResponseProto) ProtoMessage() {}

func (x *CheckForDecommissioningNodesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForDecommissioningNodesResponseProto.ProtoReflect.Descriptor instead.
func (*CheckForDecommissioningNodesResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{26}
}

func (x *CheckForDecommissioningNodesResponseProto) GetDecommissioningNodes() []*hadoopyarn.NodeIdProto {
	if x != nil {
		return x.DecommissioningNodes
	}
	return nil
}

type RefreshClusterMaxPriorityRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshClusterMaxPriorityRequestProto) Reset() {
	*x = RefreshClusterMaxPriorityRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshClusterMaxPriorityRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshClusterMaxPriorityRequestProto) ProtoMessage() {}

func (x *RefreshClusterMaxPriorityRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshClusterMaxPriorityRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshClusterMaxPriorityRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{27}
}

type RefreshClusterMaxPriorityResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshClusterMaxPriorityResponseProto) Reset() {
	*x = RefreshClusterMaxPriorityResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshClusterMaxPriorityResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshClusterMaxPriorityResponseProto) ProtoMessage() {}

func (x *RefreshClusterMaxPriorityResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshClusterMaxPriorityResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshClusterMaxPriorityResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{28}
}

type NodeIdToLabelsNameProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId     *hadoopyarn.NodeIdProto `protobuf:"bytes,1,opt,name=nodeId" json:"nodeId,omitempty"`
	NodeLabels []string                `protobuf:"bytes,2,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
}

func (x *NodeIdToLabelsNameProto) Reset() {
	*x = NodeIdToLabelsNameProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeIdToLabelsNameProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdToLabelsNameProto) ProtoMessage() {}

func (x *NodeIdToLabelsNameProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdToLabelsNameProto.ProtoReflect.Descriptor instead.
func (*NodeIdToLabelsNameProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{29}
}

func (x *NodeIdToLabelsNameProto) GetNodeId() *hadoopyarn.NodeIdProto {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *NodeIdToLabelsNameProto) GetNodeLabels() []string {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

type NodesToAttributesMappingRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation          *AttributeMappingOperationTypeProto `protobuf:"varint,1,opt,name=operation,enum=hadoop.yarn.AttributeMappingOperationTypeProto,def=1" json:"operation,omitempty"`
	NodeToAttributes   []*hadoopyarn.NodeToAttributesProto `protobuf:"bytes,2,rep,name=nodeToAttributes" json:"nodeToAttributes,omitempty"`
	FailOnUnknownNodes *bool                               `protobuf:"varint,3,opt,name=failOnUnknownNodes" json:"failOnUnknownNodes,omitempty"`
}

// Default values for NodesToAttributesMappingRequestProto fields.
const (
	Default_NodesToAttributesMappingRequestProto_Operation = AttributeMappingOperationTypeProto_REPLACE
)

func (x *NodesToAttributesMappingRequestProto) Reset() {
	*x = NodesToAttributesMappingRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodesToAttributesMappingRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesToAttributesMappingRequestProto) ProtoMessage() {}

func (x *NodesToAttributesMappingRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesToAttributesMappingRequestProto.ProtoReflect.Descriptor instead.
func (*NodesToAttributesMappingRequestProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{30}
}

func (x *NodesToAttributesMappingRequestProto) GetOperation() AttributeMappingOperationTypeProto {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return Default_NodesToAttributesMappingRequestProto_Operation
}

func (x *NodesToAttributesMappingRequestProto) GetNodeToAttributes() []*hadoopyarn.NodeToAttributesProto {
	if x != nil {
		return x.NodeToAttributes
	}
	return nil
}

func (x *NodesToAttributesMappingRequestProto) GetFailOnUnknownNodes() bool {
	if x != nil && x.FailOnUnknownNodes != nil {
		return *x.FailOnUnknownNodes
	}
	return false
}

type NodesToAttributesMappingResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NodesToAttributesMappingResponseProto) Reset() {
	*x = NodesToAttributesMappingResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodesToAttributesMappingResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesToAttributesMappingResponseProto) ProtoMessage() {}

func (x *NodesToAttributesMappingResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesToAttributesMappingResponseProto.ProtoReflect.Descriptor instead.
func (*NodesToAttributesMappingResponseProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{31}
}

//////////////////////////////////////////////////////////////////
///////////// RM Failover related records ////////////////////////
//////////////////////////////////////////////////////////////////
type ActiveRMInfoProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterId *string `protobuf:"bytes,1,opt,name=clusterId" json:"clusterId,omitempty"`
	RmId      *string `protobuf:"bytes,2,opt,name=rmId" json:"rmId,omitempty"`
}

func (x *ActiveRMInfoProto) Reset() {
	*x = ActiveRMInfoProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveRMInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveRMInfoProto) ProtoMessage() {}

func (x *ActiveRMInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_yarn_server_resourcemanager_service_protos_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveRMInfoProto.ProtoReflect.Descriptor instead.
func (*ActiveRMInfoProto) Descriptor() ([]byte, []int) {
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{32}
}

func (x *ActiveRMInfoProto) GetClusterId() string {
	if x != nil && x.ClusterId != nil {
		return *x.ClusterId
	}
	return ""
}

func (x *ActiveRMInfoProto) GetRmId() string {
	if x != nil && x.RmId != nil {
		return *x.RmId
	}
	return ""
}

var File_yarn_server_resourcemanager_service_protos_proto protoreflect.FileDescriptor

var file_yarn_server_resourcemanager_service_protos_proto_rawDesc = []byte{
	0x0a, 0x30, 0x79, 0x61, 0x72, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x1a,
	0x11, 0x79, 0x61, 0x72, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x1c, 0x0a, 0x1a, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x01,
	0x0a, 0x18, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x56, 0x0a, 0x10, 0x64, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x79, 0x61,
	0x72, 0x6e, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x3a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c,
	0x52, 0x10, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x13, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x31, 0x0a, 0x2f, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x53, 0x75, 0x70, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x30, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x53,
	0x75, 0x70, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x27, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x28, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73,
	0x65, 0x72, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41,
	0x63, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41,
	0x63, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x20, 0x0a, 0x1e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x63, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x21, 0x0a, 0x1f, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x37, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x22, 0x6f, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x4d, 0x0a, 0x11, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x52, 0x0f, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4d, 0x61, 0x70, 0x22, 0x21, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x21, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x22, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x95, 0x01, 0x0a, 0x22, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x32, 0x0a, 0x14, 0x64, 0x65, 0x70, 0x72,
	0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x3b, 0x0a, 0x0a,
	0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0a, 0x6e,
	0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x25, 0x0a, 0x23, 0x41, 0x64, 0x64,
	0x54, 0x6f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x49, 0x0a, 0x27, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x6e,
	0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x2a, 0x0a, 0x28, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x1f, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x4f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x44, 0x0a, 0x0c, 0x6e,
	0x6f, 0x64, 0x65, 0x54, 0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x54, 0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x12, 0x2e, 0x0a, 0x12, 0x66, 0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x66,
	0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x22, 0x22, 0x0a, 0x20, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x4f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x28, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46,
	0x6f, 0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e,
	0x67, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x79, 0x0a, 0x29, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x6f, 0x72, 0x44, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x4c, 0x0a, 0x14, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69,
	0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x14, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x27, 0x0a,
	0x25, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x61, 0x78, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x26, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x6b, 0x0a, 0x17, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x54, 0x6f, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x30, 0x0a, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0xfe, 0x01,
	0x0a, 0x24, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x54, 0x6f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x56, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x68, 0x61, 0x64, 0x6f,
	0x6f, 0x70, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x3a, 0x07, 0x52, 0x45, 0x50, 0x4c,
	0x41, 0x43, 0x45, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4e,
	0x0a, 0x10, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f,
	0x70, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x10, 0x6e, 0x6f,
	0x64, 0x65, 0x54, 0x6f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x2e,
	0x0a, 0x12, 0x66, 0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x66, 0x61, 0x69, 0x6c,
	0x4f, 0x6e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x27,
	0x0a, 0x25, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x54, 0x6f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x52, 0x4d, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6d,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6d, 0x49, 0x64, 0x2a, 0x3f,
	0x0a, 0x15, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41,
	0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x52, 0x41, 0x43, 0x45, 0x46, 0x55, 0x4c, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x46, 0x55, 0x4c, 0x10, 0x03, 0x2a,
	0x46, 0x0a, 0x22, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x03, 0x42, 0x4c, 0x0a, 0x1c, 0x6f, 0x72, 0x67, 0x2e, 0x61,
	0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x79, 0x61, 0x72,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x26, 0x59, 0x61, 0x72, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x88,
	0x01, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_yarn_server_resourcemanager_service_protos_proto_rawDescOnce sync.Once
	file_yarn_server_resourcemanager_service_protos_proto_rawDescData = file_yarn_server_resourcemanager_service_protos_proto_rawDesc
)

func file_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP() []byte {
	file_yarn_server_resourcemanager_service_protos_proto_rawDescOnce.Do(func() {
		file_yarn_server_resourcemanager_service_protos_proto_rawDescData = protoimpl.X.CompressGZIP(file_yarn_server_resourcemanager_service_protos_proto_rawDescData)
	})
	return file_yarn_server_resourcemanager_service_protos_proto_rawDescData
}

var file_yarn_server_resourcemanager_service_protos_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_yarn_server_resourcemanager_service_protos_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_yarn_server_resourcemanager_service_protos_proto_goTypes = []interface{}{
	(DecommissionTypeProto)(0),                               // 0: hadoop.yarn.DecommissionTypeProto
	(AttributeMappingOperationTypeProto)(0),                  // 1: hadoop.yarn.AttributeMappingOperationTypeProto
	(*RefreshQueuesRequestProto)(nil),                        // 2: hadoop.yarn.RefreshQueuesRequestProto
	(*RefreshQueuesResponseProto)(nil),                       // 3: hadoop.yarn.RefreshQueuesResponseProto
	(*RefreshNodesRequestProto)(nil),                         // 4: hadoop.yarn.RefreshNodesRequestProto
	(*RefreshNodesResponseProto)(nil),                        // 5: hadoop.yarn.RefreshNodesResponseProto
	(*RefreshSuperUserGroupsConfigurationRequestProto)(nil),  // 6: hadoop.yarn.RefreshSuperUserGroupsConfigurationRequestProto
	(*RefreshSuperUserGroupsConfigurationResponseProto)(nil), // 7: hadoop.yarn.RefreshSuperUserGroupsConfigurationResponseProto
	(*RefreshUserToGroupsMappingsRequestProto)(nil),          // 8: hadoop.yarn.RefreshUserToGroupsMappingsRequestProto
	(*RefreshUserToGroupsMappingsResponseProto)(nil),         // 9: hadoop.yarn.RefreshUserToGroupsMappingsResponseProto
	(*RefreshAdminAclsRequestProto)(nil),                     // 10: hadoop.yarn.RefreshAdminAclsRequestProto
	(*RefreshAdminAclsResponseProto)(nil),                    // 11: hadoop.yarn.RefreshAdminAclsResponseProto
	(*RefreshServiceAclsRequestProto)(nil),                   // 12: hadoop.yarn.RefreshServiceAclsRequestProto
	(*RefreshServiceAclsResponseProto)(nil),                  // 13: hadoop.yarn.RefreshServiceAclsResponseProto
	(*GetGroupsForUserRequestProto)(nil),                     // 14: hadoop.yarn.GetGroupsForUserRequestProto
	(*GetGroupsForUserResponseProto)(nil),                    // 15: hadoop.yarn.GetGroupsForUserResponseProto
	(*UpdateNodeResourceRequestProto)(nil),                   // 16: hadoop.yarn.UpdateNodeResourceRequestProto
	(*UpdateNodeResourceResponseProto)(nil),                  // 17: hadoop.yarn.UpdateNodeResourceResponseProto
	(*RefreshNodesResourcesRequestProto)(nil),                // 18: hadoop.yarn.RefreshNodesResourcesRequestProto
	(*RefreshNodesResourcesResponseProto)(nil),               // 19: hadoop.yarn.RefreshNodesResourcesResponseProto
	(*AddToClusterNodeLabelsRequestProto)(nil),               // 20: hadoop.yarn.AddToClusterNodeLabelsRequestProto
	(*AddToClusterNodeLabelsResponseProto)(nil),              // 21: hadoop.yarn.AddToClusterNodeLabelsResponseProto
	(*RemoveFromClusterNodeLabelsRequestProto)(nil),          // 22: hadoop.yarn.RemoveFromClusterNodeLabelsRequestProto
	(*RemoveFromClusterNodeLabelsResponseProto)(nil),         // 23: hadoop.yarn.RemoveFromClusterNodeLabelsResponseProto
	(*ReplaceLabelsOnNodeRequestProto)(nil),                  // 24: hadoop.yarn.ReplaceLabelsOnNodeRequestProto
	(*ReplaceLabelsOnNodeResponseProto)(nil),                 // 25: hadoop.yarn.ReplaceLabelsOnNodeResponseProto
	(*UpdateNodeLabelsResponseProto)(nil),                    // 26: hadoop.yarn.UpdateNodeLabelsResponseProto
	(*CheckForDecommissioningNodesRequestProto)(nil),         // 27: hadoop.yarn.CheckForDecommissioningNodesRequestProto
	(*CheckForDecommissioningNodesResponseProto)(nil),        // 28: hadoop.yarn.CheckForDecommissioningNodesResponseProto
	(*RefreshClusterMaxPriorityRequestProto)(nil),            // 29: hadoop.yarn.RefreshClusterMaxPriorityRequestProto
	(*RefreshClusterMaxPriorityResponseProto)(nil),           // 30: hadoop.yarn.RefreshClusterMaxPriorityResponseProto
	(*NodeIdToLabelsNameProto)(nil),                          // 31: hadoop.yarn.NodeIdToLabelsNameProto
	(*NodesToAttributesMappingRequestProto)(nil),             // 32: hadoop.yarn.NodesToAttributesMappingRequestProto
	(*NodesToAttributesMappingResponseProto)(nil),            // 33: hadoop.yarn.NodesToAttributesMappingResponseProto
	(*ActiveRMInfoProto)(nil),                                // 34: hadoop.yarn.ActiveRMInfoProto
	(*hadoopyarn.NodeResourceMapProto)(nil),                  // 35: hadoop.yarn.NodeResourceMapProto
	(*hadoopyarn.NodeLabelProto)(nil),                        // 36: hadoop.yarn.NodeLabelProto
	(*hadoopyarn.NodeIdToLabelsProto)(nil),                   // 37: hadoop.yarn.NodeIdToLabelsProto
	(*hadoopyarn.NodeIdProto)(nil),                           // 38: hadoop.yarn.NodeIdProto
	(*hadoopyarn.NodeToAttributesProto)(nil),                 // 39: hadoop.yarn.NodeToAttributesProto
}
var file_yarn_server_resourcemanager_service_protos_proto_depIdxs = []int32{
	0,  // 0: hadoop.yarn.RefreshNodesRequestProto.decommissionType:type_name -> hadoop.yarn.DecommissionTypeProto
	35, // 1: hadoop.yarn.UpdateNodeResourceRequestProto.node_resource_map:type_name -> hadoop.yarn.NodeResourceMapProto
	36, // 2: hadoop.yarn.AddToClusterNodeLabelsRequestProto.nodeLabels:type_name -> hadoop.yarn.NodeLabelProto
	37, // 3: hadoop.yarn.ReplaceLabelsOnNodeRequestProto.nodeToLabels:type_name -> hadoop.yarn.NodeIdToLabelsProto
	38, // 4: hadoop.yarn.CheckForDecommissioningNodesResponseProto.decommissioningNodes:type_name -> hadoop.yarn.NodeIdProto
	38, // 5: hadoop.yarn.NodeIdToLabelsNameProto.nodeId:type_name -> hadoop.yarn.NodeIdProto
	1,  // 6: hadoop.yarn.NodesToAttributesMappingRequestProto.operation:type_name -> hadoop.yarn.AttributeMappingOperationTypeProto
	39, // 7: hadoop.yarn.NodesToAttributesMappingRequestProto.nodeToAttributes:type_name -> hadoop.yarn.NodeToAttributesProto
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_yarn_server_resourcemanager_service_protos_proto_init() }
func file_yarn_server_resourcemanager_service_protos_proto_init() {
	if File_yarn_server_resourcemanager_service_protos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshQueuesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshQueuesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNodesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNodesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshSuperUserGroupsConfigurationRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshSuperUserGroupsConfigurationResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshUserToGroupsMappingsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshUserToGroupsMappingsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAdminAclsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAdminAclsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshServiceAclsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshServiceAclsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupsForUserRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupsForUserResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNodeResourceRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNodeResourceResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNodesResourcesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNodesResourcesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToClusterNodeLabelsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToClusterNodeLabelsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromClusterNodeLabelsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromClusterNodeLabelsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplaceLabelsOnNodeRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplaceLabelsOnNodeResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNodeLabelsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckForDecommissioningNodesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckForDecommissioningNodesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshClusterMaxPriorityRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshClusterMaxPriorityResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeIdToLabelsNameProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodesToAttributesMappingRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodesToAttributesMappingResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yarn_server_resourcemanager_service_protos_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveRMInfoProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yarn_server_resourcemanager_service_protos_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yarn_server_resourcemanager_service_protos_proto_goTypes,
		DependencyIndexes: file_yarn_server_resourcemanager_service_protos_proto_depIdxs,
		EnumInfos:         file_yarn_server_resourcemanager_service_protos_proto_enumTypes,
		MessageInfos:      file_yarn_server_resourcemanager_service_protos_proto_msgTypes,
	}.Build()
	File_yarn_server_resourcemanager_service_protos_proto = out.File
	file_yarn_server_resourcemanager_service_protos_proto_rawDesc = nil
	file_yarn_server_resourcemanager_service_protos_proto_goTypes = nil
	file_yarn_server_resourcemanager_service_protos_proto_depIdxs = nil
}
