/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/analysis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMetricPredictions implements MetricPredictionInterface
type FakeMetricPredictions struct {
	Fake *FakeAnalysisV1alpha1
	ns   string
}

var metricpredictionsResource = schema.GroupVersionResource{Group: "config.koordinator.sh", Version: "v1alpha1", Resource: "metricpredictions"}

var metricpredictionsKind = schema.GroupVersionKind{Group: "config.koordinator.sh", Version: "v1alpha1", Kind: "MetricPrediction"}

// Get takes name of the metricPrediction, and returns the corresponding metricPrediction object, and an error if there is any.
func (c *FakeMetricPredictions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MetricPrediction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(metricpredictionsResource, c.ns, name), &v1alpha1.MetricPrediction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetricPrediction), err
}

// List takes label and field selectors, and returns the list of MetricPredictions that match those selectors.
func (c *FakeMetricPredictions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MetricPredictionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(metricpredictionsResource, metricpredictionsKind, c.ns, opts), &v1alpha1.MetricPredictionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MetricPredictionList{ListMeta: obj.(*v1alpha1.MetricPredictionList).ListMeta}
	for _, item := range obj.(*v1alpha1.MetricPredictionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested metricPredictions.
func (c *FakeMetricPredictions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(metricpredictionsResource, c.ns, opts))

}

// Create takes the representation of a metricPrediction and creates it.  Returns the server's representation of the metricPrediction, and an error, if there is any.
func (c *FakeMetricPredictions) Create(ctx context.Context, metricPrediction *v1alpha1.MetricPrediction, opts v1.CreateOptions) (result *v1alpha1.MetricPrediction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(metricpredictionsResource, c.ns, metricPrediction), &v1alpha1.MetricPrediction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetricPrediction), err
}

// Update takes the representation of a metricPrediction and updates it. Returns the server's representation of the metricPrediction, and an error, if there is any.
func (c *FakeMetricPredictions) Update(ctx context.Context, metricPrediction *v1alpha1.MetricPrediction, opts v1.UpdateOptions) (result *v1alpha1.MetricPrediction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(metricpredictionsResource, c.ns, metricPrediction), &v1alpha1.MetricPrediction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetricPrediction), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMetricPredictions) UpdateStatus(ctx context.Context, metricPrediction *v1alpha1.MetricPrediction, opts v1.UpdateOptions) (*v1alpha1.MetricPrediction, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(metricpredictionsResource, "status", c.ns, metricPrediction), &v1alpha1.MetricPrediction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetricPrediction), err
}

// Delete takes name of the metricPrediction and deletes it. Returns an error if one occurs.
func (c *FakeMetricPredictions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(metricpredictionsResource, c.ns, name, opts), &v1alpha1.MetricPrediction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMetricPredictions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(metricpredictionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MetricPredictionList{})
	return err
}

// Patch applies the patch and returns the patched metricPrediction.
func (c *FakeMetricPredictions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MetricPrediction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(metricpredictionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MetricPrediction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetricPrediction), err
}
