{{- if .Values.koordlet.enableServiceMonitor }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: koordlet-metrics
  namespace: {{ .Values.installation.namespace }}
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    targetPort: {{ .Values.koordlet.metrics.port }}
  selector:
    matchLabels:
      koord-app: koordlet
{{- end }}






