apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-controller-config
  namespace: {{ .Values.installation.namespace }}
data:
  colocation-config: |
    {
      "enable": true,
      "metricAggregateDurationSeconds": 180,
      "cpuReclaimThresholdPercent": 60,
      "memoryReclaimThresholdPercent": 40,
      "memoryCalculatePolicy": "usage"
    }
  resource-threshold-config: |
    {
      "clusterStrategy": {
        "enable": true
      }
    }
  cpu-burst-config: |
    {
      "clusterStrategy": {
        "policy": "auto",
        "cpuBurstPercent": 200,
      }
    }
