/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	schedulingv1alpha1 "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/typed/scheduling/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScheduleExplanations implements ScheduleExplanationInterface
type fakeScheduleExplanations struct {
	*gentype.FakeClientWithList[*v1alpha1.ScheduleExplanation, *v1alpha1.ScheduleExplanationList]
	Fake *FakeSchedulingV1alpha1
}

func newFakeScheduleExplanations(fake *FakeSchedulingV1alpha1, namespace string) schedulingv1alpha1.ScheduleExplanationInterface {
	return &fakeScheduleExplanations{
		gentype.NewFakeClientWithList[*v1alpha1.ScheduleExplanation, *v1alpha1.ScheduleExplanationList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("scheduleexplanations"),
			v1alpha1.SchemeGroupVersion.WithKind("ScheduleExplanation"),
			func() *v1alpha1.ScheduleExplanation { return &v1alpha1.ScheduleExplanation{} },
			func() *v1alpha1.ScheduleExplanationList { return &v1alpha1.ScheduleExplanationList{} },
			func(dst, src *v1alpha1.ScheduleExplanationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ScheduleExplanationList) []*v1alpha1.ScheduleExplanation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ScheduleExplanationList, items []*v1alpha1.ScheduleExplanation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
