/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/scheduling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScheduleExplanations implements ScheduleExplanationInterface
type FakeScheduleExplanations struct {
	Fake *FakeSchedulingV1alpha1
	ns   string
}

var scheduleexplanationsResource = v1alpha1.SchemeGroupVersion.WithResource("scheduleexplanations")

var scheduleexplanationsKind = v1alpha1.SchemeGroupVersion.WithKind("ScheduleExplanation")

// Get takes name of the scheduleExplanation, and returns the corresponding scheduleExplanation object, and an error if there is any.
func (c *FakeScheduleExplanations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ScheduleExplanation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scheduleexplanationsResource, c.ns, name), &v1alpha1.ScheduleExplanation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduleExplanation), err
}

// List takes label and field selectors, and returns the list of ScheduleExplanations that match those selectors.
func (c *FakeScheduleExplanations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ScheduleExplanationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scheduleexplanationsResource, scheduleexplanationsKind, c.ns, opts), &v1alpha1.ScheduleExplanationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ScheduleExplanationList{ListMeta: obj.(*v1alpha1.ScheduleExplanationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ScheduleExplanationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scheduleExplanations.
func (c *FakeScheduleExplanations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scheduleexplanationsResource, c.ns, opts))

}

// Create takes the representation of a scheduleExplanation and creates it.  Returns the server's representation of the scheduleExplanation, and an error, if there is any.
func (c *FakeScheduleExplanations) Create(ctx context.Context, scheduleExplanation *v1alpha1.ScheduleExplanation, opts v1.CreateOptions) (result *v1alpha1.ScheduleExplanation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scheduleexplanationsResource, c.ns, scheduleExplanation), &v1alpha1.ScheduleExplanation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduleExplanation), err
}

// Update takes the representation of a scheduleExplanation and updates it. Returns the server's representation of the scheduleExplanation, and an error, if there is any.
func (c *FakeScheduleExplanations) Update(ctx context.Context, scheduleExplanation *v1alpha1.ScheduleExplanation, opts v1.UpdateOptions) (result *v1alpha1.ScheduleExplanation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scheduleexplanationsResource, c.ns, scheduleExplanation), &v1alpha1.ScheduleExplanation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduleExplanation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeScheduleExplanations) UpdateStatus(ctx context.Context, scheduleExplanation *v1alpha1.ScheduleExplanation, opts v1.UpdateOptions) (*v1alpha1.ScheduleExplanation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(scheduleexplanationsResource, "status", c.ns, scheduleExplanation), &v1alpha1.ScheduleExplanation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduleExplanation), err
}

// Delete takes name of the scheduleExplanation and deletes it. Returns an error if one occurs.
func (c *FakeScheduleExplanations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(scheduleexplanationsResource, c.ns, name, opts), &v1alpha1.ScheduleExplanation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScheduleExplanations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scheduleexplanationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ScheduleExplanationList{})
	return err
}

// Patch applies the patch and returns the patched scheduleExplanation.
func (c *FakeScheduleExplanations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ScheduleExplanation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scheduleexplanationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ScheduleExplanation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduleExplanation), err
}
