apiVersion: v1
kind: Service
metadata:
  labels:
    koord-app: koord-manager
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    koord-app: koord-manager
