
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: system
  name: koordlet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: koordlet-role
rules:
- apiGroups:
    - config.koordinator.sh
    - slo.koordinator.sh
    - scheduling.koordinator.sh
    - topology.node.k8s.io
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - configmaps
    - configmaps/status
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - nodes
    - nodes/status
    - nodes/proxy
    - pods
    - pods/status
    - persistentvolumeclaims
    - persistentvolumeclaims/status
  verbs:
    - patch
    - update
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods/eviction
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: koordlet-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: koordlet-role
subjects:
  - kind: ServiceAccount
    name: koordlet
    namespace: system
