# permissions for end users to edit nodemetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodemetric-editor-role
rules:
- apiGroups:
  - slo.koordinator.sh
  resources:
  - nodemetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slo.koordinator.sh
  resources:
  - nodemetrics/status
  verbs:
  - get
