apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.koordinator.sh
  - slo.koordinator.sh
  - scheduling.koordinator.sh
  - topology.node.k8s.io
  - scheduling.sigs.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
