{{- if .Values.aiCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: hybrid-ai-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "hybrid.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.aiCredentials.server }}
  AI_SERVER: {{ .Values.aiCredentials.server | b64enc | quote }}
  {{- end }}
  {{- if .Values.aiCredentials.token }}
  AI_TOKEN: {{ .Values.aiCredentials.token | b64enc | quote }}
  {{- end }}
{{- end }}