/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	quotav1alpha1 "github.com/koordinator-sh/koordinator/apis/quota/v1alpha1"
	scheme "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ElasticQuotaProfilesGetter has a method to return a ElasticQuotaProfileInterface.
// A group's client should implement this interface.
type ElasticQuotaProfilesGetter interface {
	ElasticQuotaProfiles(namespace string) ElasticQuotaProfileInterface
}

// ElasticQuotaProfileInterface has methods to work with ElasticQuotaProfile resources.
type ElasticQuotaProfileInterface interface {
	Create(ctx context.Context, elasticQuotaProfile *quotav1alpha1.ElasticQuotaProfile, opts v1.CreateOptions) (*quotav1alpha1.ElasticQuotaProfile, error)
	Update(ctx context.Context, elasticQuotaProfile *quotav1alpha1.ElasticQuotaProfile, opts v1.UpdateOptions) (*quotav1alpha1.ElasticQuotaProfile, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, elasticQuotaProfile *quotav1alpha1.ElasticQuotaProfile, opts v1.UpdateOptions) (*quotav1alpha1.ElasticQuotaProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*quotav1alpha1.ElasticQuotaProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*quotav1alpha1.ElasticQuotaProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *quotav1alpha1.ElasticQuotaProfile, err error)
	ElasticQuotaProfileExpansion
}

// elasticQuotaProfiles implements ElasticQuotaProfileInterface
type elasticQuotaProfiles struct {
	*gentype.ClientWithList[*quotav1alpha1.ElasticQuotaProfile, *quotav1alpha1.ElasticQuotaProfileList]
}

// newElasticQuotaProfiles returns a ElasticQuotaProfiles
func newElasticQuotaProfiles(c *QuotaV1alpha1Client, namespace string) *elasticQuotaProfiles {
	return &elasticQuotaProfiles{
		gentype.NewClientWithList[*quotav1alpha1.ElasticQuotaProfile, *quotav1alpha1.ElasticQuotaProfileList](
			"elasticquotaprofiles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *quotav1alpha1.ElasticQuotaProfile { return &quotav1alpha1.ElasticQuotaProfile{} },
			func() *quotav1alpha1.ElasticQuotaProfileList { return &quotav1alpha1.ElasticQuotaProfileList{} },
		),
	}
}
