/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/koordlet/runtimehooks/nri/types.go

// Package nri is a generated GoMock package.
package nri

import (
	context "context"
	reflect "reflect"
	time "time"

	api "github.com/containerd/nri/pkg/api"
	gomock "github.com/golang/mock/gomock"
)

// MockStubInterface is a mock of StubInterface interface.
type MockStubInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStubInterfaceMockRecorder
}

// MockStubInterfaceMockRecorder is the mock recorder for MockStubInterface.
type MockStubInterfaceMockRecorder struct {
	mock *MockStubInterface
}

// NewMockStubInterface creates a new mock instance.
func NewMockStubInterface(ctrl *gomock.Controller) *MockStubInterface {
	mock := &MockStubInterface{ctrl: ctrl}
	mock.recorder = &MockStubInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStubInterface) EXPECT() *MockStubInterfaceMockRecorder {
	return m.recorder
}

// RegistrationTimeout mocks base method.
func (m *MockStubInterface) RegistrationTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegistrationTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// RegistrationTimeout indicates an expected call of RegistrationTimeout.
func (mr *MockStubInterfaceMockRecorder) RegistrationTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegistrationTimeout", reflect.TypeOf((*MockStubInterface)(nil).RegistrationTimeout))
}

// RequestTimeout mocks base method.
func (m *MockStubInterface) RequestTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// RequestTimeout indicates an expected call of RequestTimeout.
func (mr *MockStubInterfaceMockRecorder) RequestTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestTimeout", reflect.TypeOf((*MockStubInterface)(nil).RequestTimeout))
}

// Run mocks base method.
func (m *MockStubInterface) Run(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockStubInterfaceMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockStubInterface)(nil).Run), arg0)
}

// Start mocks base method.
func (m *MockStubInterface) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockStubInterfaceMockRecorder) Start(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStubInterface)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockStubInterface) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockStubInterfaceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockStubInterface)(nil).Stop))
}

// UpdateContainers mocks base method.
func (m *MockStubInterface) UpdateContainers(arg0 []*api.ContainerUpdate) ([]*api.ContainerUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContainers", arg0)
	ret0, _ := ret[0].([]*api.ContainerUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContainers indicates an expected call of UpdateContainers.
func (mr *MockStubInterfaceMockRecorder) UpdateContainers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContainers", reflect.TypeOf((*MockStubInterface)(nil).UpdateContainers), arg0)
}

// Wait mocks base method.
func (m *MockStubInterface) Wait() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wait")
}

// Wait indicates an expected call of Wait.
func (mr *MockStubInterfaceMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockStubInterface)(nil).Wait))
}

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// Configure mocks base method.
func (m *MockServer) Configure(ctx context.Context, config, runtime, version string) (api.EventMask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Configure", ctx, config, runtime, version)
	ret0, _ := ret[0].(api.EventMask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Configure indicates an expected call of Configure.
func (mr *MockServerMockRecorder) Configure(ctx, config, runtime, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockServer)(nil).Configure), ctx, config, runtime, version)
}

// CreateContainer mocks base method.
func (m *MockServer) CreateContainer(arg0 context.Context, arg1 *api.PodSandbox, arg2 *api.Container) (*api.ContainerAdjustment, []*api.ContainerUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContainer", arg0, arg1, arg2)
	ret0, _ := ret[0].(*api.ContainerAdjustment)
	ret1, _ := ret[1].([]*api.ContainerUpdate)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockServerMockRecorder) CreateContainer(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContainer", reflect.TypeOf((*MockServer)(nil).CreateContainer), arg0, arg1, arg2)
}

// RemovePodSandbox mocks base method.
func (m *MockServer) RemovePodSandbox(arg0 context.Context, arg1 *api.PodSandbox) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePodSandbox", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePodSandbox indicates an expected call of RemovePodSandbox.
func (mr *MockServerMockRecorder) RemovePodSandbox(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePodSandbox", reflect.TypeOf((*MockServer)(nil).RemovePodSandbox), arg0, arg1)
}

// RunPodSandbox mocks base method.
func (m *MockServer) RunPodSandbox(arg0 context.Context, arg1 *api.PodSandbox) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunPodSandbox", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunPodSandbox indicates an expected call of RunPodSandbox.
func (mr *MockServerMockRecorder) RunPodSandbox(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPodSandbox", reflect.TypeOf((*MockServer)(nil).RunPodSandbox), arg0, arg1)
}

// Start mocks base method.
func (m *MockServer) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockServer)(nil).Start))
}

// Synchronize mocks base method.
func (m *MockServer) Synchronize(arg0 context.Context, arg1 []*api.PodSandbox, arg2 []*api.Container) ([]*api.ContainerUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Synchronize", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*api.ContainerUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Synchronize indicates an expected call of Synchronize.
func (mr *MockServerMockRecorder) Synchronize(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Synchronize", reflect.TypeOf((*MockServer)(nil).Synchronize), arg0, arg1, arg2)
}

// UpdateContainer mocks base method.
func (m *MockServer) UpdateContainer(arg0 context.Context, arg1 *api.PodSandbox, arg2 *api.Container, arg3 *api.LinuxResources) ([]*api.ContainerUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContainer", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*api.ContainerUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContainer indicates an expected call of UpdateContainer.
func (mr *MockServerMockRecorder) UpdateContainer(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContainer", reflect.TypeOf((*MockServer)(nil).UpdateContainer), arg0, arg1, arg2, arg3)
}
