/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	slov1alpha1 "github.com/koordinator-sh/koordinator/apis/slo/v1alpha1"
	scheme "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NodeMetricsGetter has a method to return a NodeMetricInterface.
// A group's client should implement this interface.
type NodeMetricsGetter interface {
	NodeMetrics() NodeMetricInterface
}

// NodeMetricInterface has methods to work with NodeMetric resources.
type NodeMetricInterface interface {
	Create(ctx context.Context, nodeMetric *slov1alpha1.NodeMetric, opts v1.CreateOptions) (*slov1alpha1.NodeMetric, error)
	Update(ctx context.Context, nodeMetric *slov1alpha1.NodeMetric, opts v1.UpdateOptions) (*slov1alpha1.NodeMetric, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, nodeMetric *slov1alpha1.NodeMetric, opts v1.UpdateOptions) (*slov1alpha1.NodeMetric, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*slov1alpha1.NodeMetric, error)
	List(ctx context.Context, opts v1.ListOptions) (*slov1alpha1.NodeMetricList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *slov1alpha1.NodeMetric, err error)
	NodeMetricExpansion
}

// nodeMetrics implements NodeMetricInterface
type nodeMetrics struct {
	*gentype.ClientWithList[*slov1alpha1.NodeMetric, *slov1alpha1.NodeMetricList]
}

// newNodeMetrics returns a NodeMetrics
func newNodeMetrics(c *SloV1alpha1Client) *nodeMetrics {
	return &nodeMetrics{
		gentype.NewClientWithList[*slov1alpha1.NodeMetric, *slov1alpha1.NodeMetricList](
			"nodemetrics",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *slov1alpha1.NodeMetric { return &slov1alpha1.NodeMetric{} },
			func() *slov1alpha1.NodeMetricList { return &slov1alpha1.NodeMetricList{} },
		),
	}
}
