apiVersion: v1
kind: Namespace
metadata:
  name: koord-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: koord-controller-config
  namespace: koord-system
data:
  colocation-config: |
    {
      "enable": true,
      "metricAggregateDurationSeconds": 60
    }