apiVersion: v1
kind: ServiceAccount
metadata:
  name: koord-controller
  namespace: koord-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koord-controller-role:leaderelection
  namespace: koord-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/status
    verbs:
      - get
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: koord-controller-custom-rolebinding:leaderelection
  namespace: koord-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koord-controller-role:leaderelection
subjects:
  - kind: ServiceAccount
    name: koord-controller
    namespace: koord-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: koord-controller-custom-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: koord-controller-cluserrole
subjects:
  - kind: ServiceAccount
    name: koord-controller
    namespace: koord-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: koord-controller-cluserrole
rules:
  - apiGroups:
      - config.koordinator.sh
      - slo.koordinator.sh
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/status
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
      - pods
      - pods/status
    verbs:
      - patch
      - update
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - '*'
