apiVersion: v1
kind: Secret
metadata:
  name: hybrid-ai-credentials
  namespace: hybrid-system
type: Opaque
data:
  # 替换为真实 url
  AI_SERVER: aHR0cDovLzEwLjY0LjcuMjMwOjgwMDA=
  # 替换为真实 token
  AI_TOKEN: YUdWc2JHOHNjSGwwYUc5dWxRPT0=
