name: License

on:
  push:
    branches:
      - main
      - release-*
  pull_request: {}
  workflow_dispatch: {}

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Check license
        run: |
          gem install license_finder
          license_finder --decisions_file .license/dependency_decisions.yml
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version-file: go.mod
      - name: Check license header
        run: |
          make lint-license && git add apis pkg cmd test || exit 1
          git diff --cached --exit-code || (echo 'Please run "make lint-license" to verify license header' && exit 1);
