name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GITHUB_REG: ghcr.io
      ALIYUN_BJ_REG: registry.cn-beijing.aliyuncs.com
      ALIYUN_HZ_REG: registry.cn-hangzhou.aliyuncs.com
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_REG }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to AliyunCS_BJ
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ALIYUN_BJ_REG }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PWD }}
      - name: Login to AliyunCS_HZ
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ALIYUN_HZ_REG }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PWD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
